import SupportLayout from "../SupportLayout";

export default function Privacy() {
  return (
    <SupportLayout icon="fa-shield-halved" title="Privacy Policy">
      <div className="support-section">
        <h2>Information We Collect</h2>
        <p>We collect information you provide directly (name, email, phone), data generated by your use of the platform (ride history, location), and technical data (device type, IP address, browser type).</p>
      </div>
      <div className="support-section">
        <h2>How We Use Your Information</h2>
        <p>Your data is used to provide and improve our services, match passengers with drivers, process payments, send service notifications, and ensure platform safety and security.</p>
      </div>
      <div className="support-section">
        <h2>Data Sharing</h2>
        <p>We do not sell your personal data. We may share data with drivers (only what's necessary for a ride), payment processors, and legal authorities when required by law.</p>
      </div>
      <div className="support-section">
        <h2>Data Security</h2>
        <p>All data is encrypted in transit and at rest. We use industry-standard security practices and conduct regular audits to protect your information.</p>
      </div>
      <div className="support-section">
        <h2>Your Rights</h2>
        <p>You have the right to access, correct, or delete your personal data. Contact privacy@safego.com to exercise these rights.</p>
      </div>
    </SupportLayout>
  );
}
